# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fusiondatacli < Formula
  desc "Terminal browser for Autodesk Platform Services Manufacturing Data Model"
  homepage "https://github.com/schneik80/FusionDataCLI"
  version "2.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v2.0.5/FusionDataCLI-2.0.5-darwin-amd64.tar.gz"
      sha256 "80ef86dd517e9010dc88dd8597df150831f77d3334f4246b8f14ed8872618038"

      define_method(:install) do
        bin.install "fusiondatacli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v2.0.5/FusionDataCLI-2.0.5-darwin-arm64.tar.gz"
      sha256 "9ef0389d931de0f236aae97b3c64abaf39716899c70de17520c45c30fc91efe0"

      define_method(:install) do
        bin.install "fusiondatacli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v2.0.5/FusionDataCLI-2.0.5-linux-amd64.tar.gz"
      sha256 "0bc24903a2edd64084e2edd99638cb54168503fc7b64f7b5efe3bbad86111bcc"
      define_method(:install) do
        bin.install "fusiondatacli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v2.0.5/FusionDataCLI-2.0.5-linux-arm64.tar.gz"
      sha256 "ea2bbda464458d05c6e3acfd7d8a8901e00e63db033ef1ede9f9e4c8028d4964"
      define_method(:install) do
        bin.install "fusiondatacli"
      end
    end
  end
end
