# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Fusiondatacli < Formula
  desc "Terminal browser for autodesk platform services (aps) manufacturing data model"
  homepage "https://github.com/schneik80/FusionDataCLI"
  url "https://github.com/schneik80/FusionDataCLI/archive/refs/tags/v0.3.1.tar.gz"
  sha256 "f80dc5f8aecd7618b8e405bcff34e4aa6db943c049358369085f499933ff5ae0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v0.3.1/FusionDataCLI-0.3.1-darwin-amd64.tar.gz"
      sha256 "630ec2a81de186548d075e49314b61215e395eaea2ca19d8f0e268f0efd00800"
    end

    on_arm do
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v0.3.1/FusionDataCLI-0.3.1-darwin-arm64.tar.gz"
      sha256 "48782b5b62e2f045da7fe688951912bc346a0e6a416af8a5ceabf1b14fdca74c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v0.3.1/FusionDataCLI-0.3.1-linux-amd64.tar.gz"
      sha256 "9d9a8c0135ec42c3bedf528ffeb6c71c2c0542906b69afb8228f1c6908a140fd"
    end

    on_arm do
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v0.3.1/FusionDataCLI-0.3.1-linux-arm64.tar.gz"
      sha256 "78a95a8b3f2ee83dba017be0a30d0f635a752b0432b489a9acc334f29c34e3ba"
    end
  end

  def install
    bin.install "fusiondatacli"
  end
end
