# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fusiondatacli < Formula
  desc "Terminal browser for Autodesk Platform Services Manufacturing Data Model"
  homepage "https://github.com/schneik80/FusionDataCLI"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v2.0.1/FusionDataCLI-2.0.1-darwin-amd64.tar.gz"
      sha256 "141739dc003439d1e01c9df7c4c9fc1eefab19a38217a62bdb778c90804ce35f"

      define_method(:install) do
        bin.install "fusiondatacli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v2.0.1/FusionDataCLI-2.0.1-darwin-arm64.tar.gz"
      sha256 "68f9db9b020c36a24bb67292901bdabd65e12446830493fc46958c78e68db220"

      define_method(:install) do
        bin.install "fusiondatacli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v2.0.1/FusionDataCLI-2.0.1-linux-amd64.tar.gz"
      sha256 "be082515bbd7db72a2177cce3900bbf1de8e04173737373ae1b0e842ec7024e3"
      define_method(:install) do
        bin.install "fusiondatacli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v2.0.1/FusionDataCLI-2.0.1-linux-arm64.tar.gz"
      sha256 "45a9d7f2d0c7f3215383f4b1302120b2a16d3063ad1c3c23d96dd9d15bc21d52"
      define_method(:install) do
        bin.install "fusiondatacli"
      end
    end
  end
end
