# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Fusiondatacli < Formula
  desc "Terminal browser for autodesk platform services (aps) manufacturing data model"
  homepage "https://github.com/schneik80/FusionDataCLI"
  url "https://github.com/schneik80/FusionDataCLI/archive/refs/tags/v0.3.0.tar.gz"
  sha256 "9dc27d1058b73bbff2ee1911a78ad1edbc4726e3b4b5c9f8abe7575b6cca106f"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v0.3.0/FusionDataCLI-0.3.0-darwin-amd64.tar.gz"
      sha256 "e14b7ebd2d2d7a6dc97761d0de5821eddf98d138158d1e43a9b83fdf0f6468f0"
    end

    on_arm do
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v0.3.0/FusionDataCLI-0.3.0-darwin-arm64.tar.gz"
      sha256 "56175bd152898e3729359b7326b22483b114f7931cb335acad2096e579cc335c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v0.3.0/FusionDataCLI-0.3.0-linux-amd64.tar.gz"
      sha256 "8ad3118c7e9f9c022b93169a6860eafde3b9502937e7f5cd3eb49c6243570dda"
    end

    on_arm do
      url "https://github.com/schneik80/FusionDataCLI/releases/download/v0.3.0/FusionDataCLI-0.3.0-linux-arm64.tar.gz"
      sha256 "d01f269c5955bbf0cb9023a4f3767c0ac52ec262d0fea4d1ab238a2768a63067"
    end
  end

  def install
    bin.install "fusiondatacli"
  end
end
